### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by DZITs** [angelwzr/darker#3]
First of all I'd like to say thank you for the application, it is very handy and lightweight.
At the moment Darker is some sort of portable application, and it is needed to place executable somewhere to work.
That would be nice option to distribute it as installer (exe or msp) instead of executable itself (or as an alternate use Windows Store for installing and updating).

**Comment by angelwzr** [comment]
@DZITs appreciate your feedback, thanks! 

Future releases will include .msix app bundle if everything goes as planned. I really want to publish it in the Store too, but I think it will happen after I add most of the planned features to the app. So in a month or so, I guess.

**Comment by DZITs** [comment]
@angelwzr great news.
Also awaiting for independent switching of system and apps themes. Keep posted.

**Comment by Saijin-Naib** [comment]
Not sure if store/published apps are allowed, but could this automate the Light/Dark theme switching based upon Sunrise/Sunset like on the Xbox?

That is just... chef kiss

**Comment by angelwzr** [comment]
@Saijin-Naib theme switching on schedule options are planned for a future release. Can be tied in with location data I guess, just like Night light in Windows 10 itself.

**Comment by Saijin-Naib** [comment]
Sweet, didn't know if those APIs would be blocked on a store-deployed app.

**Comment by angelwzr** [comment]
Setup project was added with commit 1451861fe6da1265b5e78949c7bb2020b8c1af98
