### ISSUE TITLE
Virustotal flags the installer as a virus

### ISSUE THREAD

**Issue by francesco-plt** [angelwzr/darker#7]
![image](https://user-images.githubusercontent.com/26849744/103222694-eb48d000-4924-11eb-8a4f-643951488784.png)

**Comment by francesco-plt** [comment]
Any reason why this is happening?

**Comment by rocketinventor** [comment]
Why does the installer have/need "direct-cpu-clock-access"?

**Comment by angelwzr** [comment]
Decided that we don't need installer anymore. Feature versions will continue to be portable. The current one is deleted from releases.
